// Başlangıç listesi — WhatsApp listesi + Trendyol sepetinden (22 Ağustos 2026).
// Fiyatlar o günkü Trendyol sepet fiyatları; link/görsel sonradan siteden eklenir.
window.EV_SEED = [
  // ---- ACİL ----
  { category: "acil", emoji: "🍽️", name: "Bulaşık kurutmalık", price: 599.90,
    note: "NTC Metal 2 katlı Luna (599,90) ya da Evonita sürgülü açılır-kapanır (498,99)" },
  { category: "acil", emoji: "🧴", name: "Bulaşık deterjanı" },
  { category: "acil", emoji: "🧽", name: "Sünger" },
  { category: "acil", emoji: "🍲", name: "Yemek tenceresi" },
  { category: "acil", emoji: "🍳", name: "Tava seti", price: 1372,
    note: "Taç Triton 3'lü döküm tava seti" },
  { category: "acil", emoji: "🥚", name: "Yumurta / pilav tavası" },
  { category: "acil", emoji: "🫗", name: "Sürahi" },
  { category: "acil", emoji: "🧊", name: "Buz kabı" },
  { category: "acil", emoji: "🫙", name: "Kavanoz" },
  { category: "acil", emoji: "🧂", name: "Baharat seti" },
  { category: "acil", emoji: "🍴", name: "Çatal kaşık bıçak seti" },
  { category: "acil", emoji: "🛁", name: "Mutfak ve banyo havlusu" },
  { category: "acil", emoji: "🧹", name: "Süpürge" },
  { category: "acil", emoji: "🪣", name: "Vileda / paspas" },
  { category: "acil", emoji: "🧻", name: "Peçete" },
  { category: "acil", emoji: "🧼", name: "Sabun" },
  { category: "acil", emoji: "🧺", name: "Kirli çamaşır sepeti", price: 773.25,
    note: "Bino ahşap banyo çamaşır sepeti" },

  // ---- ORTA ----
  { category: "orta", emoji: "🛋️", name: "Halı", price: 1982.07,
    note: "Vila Nova Home ekru peluş yuvarlak 190x190" },
  { category: "orta", emoji: "🗄️", name: "Komodin" },
  { category: "orta", emoji: "🪞", name: "Boy aynası", price: 1590,
    note: "Effe Yapı Dekor altın metal çerçeveli (kargo 12 gün)" },
  { category: "orta", emoji: "💄", name: "Makyaj masası", price: 3199,
    note: "Arnetti inci beyaz aynalı — montaj hizmeti ayrı" },
  { category: "orta", emoji: "🪑", name: "Makyaj masası pufu" },
  { category: "orta", emoji: "💅", name: "Makyaj organizer", price: 843,
    note: "Limeks çekmeceli (843) ya da Piev aynalı çekmeceli (549)" },
  { category: "orta", emoji: "🧵", name: "Çamaşır makinesi örtüsü", price: 181.28,
    note: "Getcarpet" },
  { category: "orta", emoji: "🥧", name: "Yuvarlak fırın tepsisi", note: "Evden alınabilir" },
  { category: "orta", emoji: "🍝", name: "Makarna süzgeci", note: "Evden alınabilir" },

  // ---- SONRA ----
  { category: "sonra", emoji: "🍟", name: "Airfryer", note: "Evden alınabilir" },
  { category: "sonra", emoji: "🥤", name: "Stanley termos" },
  { category: "sonra", emoji: "🌶️", name: "Sriracha sos" },
  { category: "sonra", emoji: "🕯️", name: "Lavanta mum", price: 512.57,
    note: "ersustore yeşil 2'li beton saksı" },
  { category: "sonra", emoji: "🪔", name: "Tütsülük", price: 372.15,
    note: "OrdoVeni ahşap dekoratif" },
  { category: "sonra", emoji: "🌸", name: "Oda kokusu seti", price: 671.20,
    note: "Rosie Masum Dokunuşlar 6'lı çubuklu" },
  { category: "sonra", emoji: "🧖", name: "Duş kesesi ve banyo lifi", price: 355.14,
    note: "LET'SCRUB sırt kesesi 355 · esnek lif 227 · eldiven kese 255" },
  { category: "sonra", emoji: "🦶", name: "Topuk ve ayak bakım kremi", note: "LET'SCRUB 75 ml" },
  { category: "sonra", emoji: "👁️", name: "Takma kirpik seti", price: 574.10,
    note: "Güzellik Deposu 580 parça" },
];
